AWSTemplateFormatVersion: "2010-09-09"
Description: VPC Configuration
Parameters:
  KeyName:
    Description: Name of KeyPair
    Type: AWS::EC2::KeyPair::KeyName
  Ec2OS:
    Description: Operating System for EC2
    Type: String
    Default: 'Amazon Linux 2023'
    AllowedValues:
      - 'Amazon Linux 2'
      - 'Amazon Linux 2023'
      - 'Windows 2019'

Mappings:
  RegionMap: 
    ap-northeast-2:
      Linux2: ami-0443a21cb1a8f238e
      Windows2019: ami-0bf1f2674712ac133
    ap-southeast-1:
      Linux2: ami-03f6a11788f8e319e
      Windows2019: ami-0712e391765a3931b
 
Resources:
  SecurityGroupWeb:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow 22, 80 port
      GroupName: WebEC2SecutiryGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !ImportValue Network-Stack-VPC
  SecurityGroupApp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow webserver traffic only
      GroupName: AppEC2SecutiryGroup
      SecurityGroupIngress:
        - IpProtocol: -1
          SourceSecurityGroupId : !GetAtt SecurityGroupWeb.GroupId
      VpcId: !ImportValue Network-Stack-VPC
 
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", !Ref Ec2OS ]
      KeyName: !Ref KeyName
      InstanceType: t3.micro
      SubnetId: !ImportValue Network-Stack-PublicSubnet01
      SecurityGroupIds:
        - !Ref SecurityGroupWeb
      UserData:
        Fn::Base64:
          !Join [ "", [
          "#!/bin/bash\n",
          "#Install APM for Web Server\n",
          "yum install -y mariadb* php httpd php-mysql\n",
          "systemctl enable httpd mariadb\n",
          "systemctl start httpd mariadb\n"] ]
      Tags:
        - Key: Name
          Value: Web-Server
  AppServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", !Ref Ec2OS ]
      KeyName: !Ref KeyName
      InstanceType: t3.micro
      SubnetId: !ImportValue Network-Stack-PrivateSubnet01
      SecurityGroupIds:
        - !Ref SecurityGroupWeb
      UserData:
        Fn::Base64:
          !Join [ "", [
          "#!/bin/bash\n",
          "#Install APM for App Server\n",
          "yum install -y tomcat\n",
          "systemctl enable tomcat\n",
          "systemctl start tomcat\n"] ]
      Tags:
        - Key: Name
          Value: App-Server